In [1]:
import pandas as pd
import numpy as np
import datetime
from google.colab import files
uploaded = files.upload()

Saving imports-85.txt to imports-85.txt

In [3]:
df_car = pd.read_csv('imports-85.txt', sep=",", header=None,na_values="?")
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       205 non-null    int64
 1   1       164 non-null    float64
 2   2       205 non-null    object
 3   3       205 non-null    object
 4   4       205 non-null    object
 5   5       203 non-null    object
 6   6       205 non-null    object
 7   7       205 non-null    object
 8   8       205 non-null    object
 9   9       205 non-null    float64
 10  10      205 non-null    float64
 11  11      205 non-null    float64
 12  12      205 non-null    float64
 13  13      205 non-null    int64
 14  14      205 non-null    object
 15  15      205 non-null    object
 16  16      205 non-null    int64
 17  17      205 non-null    object
 18  18      201 non-null    float64
 19  19      201 non-null    float64
 20  20      205 non-null    float64
 21  21      203 non-null    float64
 22  22      203 non-null    float64
 23  23      205 non-null    int64
 24  24      205 non-null    int64
 25  25      201 non-null    float64
dtypes: float64(11), int64(5), object(10)
memory usage: 41.8+ KB

In [6]:
titulos = {0:"symboling", 1:"normalized_losses", 2:"make", 3:"fuel_type", 4:"aspiration",
           5:"num_doors", 6:"body_style", 7:"drive_wheels",8: "engine_location",
           9:"wheel_base", 10:"length", 11:"width",12: "height", 13:"curb_weight",
           14:"engine_type", 15:"num_cylinders",16: "engine_size", 17:"fuel_system",
           18:"bore", 19:"stroke", 20:"compression_ratio", 21:"horsepower", 22:"peak_rpm",
           23:"city_mpg", 24:"highway_mpg", 25:"price"}

df_car.rename(columns=titulos,inplace=True)
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized_losses  164 non-null    float64
 2   make               205 non-null    object
 3   fuel_type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num_doors          203 non-null    object
 6   body_style         205 non-null    object
 7   drive_wheels       205 non-null    object
 8   engine_location    205 non-null    object
 9   wheel_base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb_weight        205 non-null    int64
 14  engine_type        205 non-null    object
 15  num_cylinders      205 non-null    object
 16  engine_size        205 non-null    int64
 17  fuel_system        205 non-null    object
 18  bore               201 non-null    float64
 19  stroke             201 non-null    float64
 20  compression_ratio  205 non-null    float64
 21  horsepower         203 non-null    float64
 22  peak_rpm           203 non-null    float64
 23  city_mpg           205 non-null    int64
 24  highway_mpg        205 non-null    int64
 25  price              201 non-null    float64
dtypes: float64(11), int64(5), object(10)
memory usage: 41.8+ KB

In [9]:
df_car_objects = df_car.select_dtypes(include=['object']).copy()

df_car_objects.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   make             205 non-null    object
 1   fuel_type        205 non-null    object
 2   aspiration       205 non-null    object
 3   num_doors        203 non-null    object
 4   body_style       205 non-null    object
 5   drive_wheels     205 non-null    object
 6   engine_location  205 non-null    object
 7   engine_type      205 non-null    object
 8   num_cylinders    205 non-null    object
 9   fuel_system      205 non-null    object
dtypes: object(10)
memory usage: 16.1+ KB

In [11]:
df_car_objects.isnull().sum()

make               0
fuel_type          0
aspiration         0
num_doors          2
body_style         0
drive_wheels       0
engine_location    0
engine_type        0
num_cylinders      0
fuel_system        0
dtype: int64

In [12]:
df_car_objects.dropna(inplace=True)
df_car_objects.isnull().sum()

make               0
fuel_type          0
aspiration         0
num_doors          0
body_style         0
drive_wheels       0
engine_location    0
engine_type        0
num_cylinders      0
fuel_system        0
dtype: int64

In [14]:
df_car_objects["num_cylinders"].value_counts()

four      157
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: num_cylinders, dtype: int64

In [17]:
map_classes = {"num_doors":     {"four": 4, "two": 2},
                "num_cylinders": {"four": 4, "six": 6, "five": 5, "eight": 8,
                                  "two": 2, "twelve": 12, "three":3 }}

In [18]:
df_car_objects.replace(map_classes, inplace=True)
df_car_objects.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 203 entries, 0 to 204
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   make             203 non-null    object
 1   fuel_type        203 non-null    object
 2   aspiration       203 non-null    object
 3   num_doors        203 non-null    int64
 4   body_style       203 non-null    object
 5   drive_wheels     203 non-null    object
 6   engine_location  203 non-null    object
 7   engine_type      203 non-null    object
 8   num_cylinders    203 non-null    int64
 9   fuel_system      203 non-null    object
dtypes: int64(2), object(8)
memory usage: 17.4+ KB

In [20]:
df_car_objects["body_style"] = df_car_objects["body_style"].astype('category')
df_car_objects.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 203 entries, 0 to 204
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   make             203 non-null    object
 1   fuel_type        203 non-null    object
 2   aspiration       203 non-null    object
 3   num_doors        203 non-null    int64
 4   body_style       203 non-null    category
 5   drive_wheels     203 non-null    object
 6   engine_location  203 non-null    object
 7   engine_type      203 non-null    object
 8   num_cylinders    203 non-null    int64
 9   fuel_system      203 non-null    object
dtypes: category(1), int64(2), object(7)
memory usage: 16.3+ KB

In [21]:
pd.get_dummies(df_car_objects, columns=["drive_wheels"]).head()

          make fuel_type  ... drive_wheels_fwd  drive_wheels_rwd
0  alfa-romero       gas  ...                0                 1
1  alfa-romero       gas  ...                0                 1
2  alfa-romero       gas  ...                0                 1
3         audi       gas  ...                1                 0
4         audi       gas  ...                0                 0

[5 rows x 12 columns]